// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://clvodvtoojxvkzfjuire.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsdm9kdnRvb2p4dmt6Zmp1aXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MzUxODYsImV4cCI6MjA3OTMxMTE4Nn0.QX8QmWyN46uOekqmFkpE73VT30ickbDX6F-7Tg-x4dE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);